### ISSUE TITLE
model giving same output prediction

### ISSUE THREAD

**Issue by max6457** [WenjieDu/PyPOTS#163] opened 2023-07-20 23:27 UTC
### Issue description

hello,
I have the problem that my trained models gives me the same output for no matter which input I have. 
Is it a problem with the data or maybe the model/my training of the model?
So here are the labels & it's amount in the dataset:
![nlabels](https://github.com/WenjieDu/PyPOTS/assets/122063689/1e8ac900-5a6e-46d8-a1e8-7ab9a0280715)

Now my problem is tht when I use the classify feature to classify my test dataset the only label which raindrop predicts is 0:

![plot_raindrop_predictions](https://github.com/WenjieDu/PyPOTS/assets/122063689/3bccab8a-41c5-4af1-a313-e3ea4d9dd880)
![raindrop_prediction2](https://github.com/WenjieDu/PyPOTS/assets/122063689/a096ab6d-4b36-4307-8452-09d4a659d7fe)

I have only trained the model for some epochs to check it because training is pricy :), but may it be that this causes this issue or should I change the data preprocessing?

**Comment by WenjieDu** [comment] 2023-07-21 02:15
Hi, I can't tell where the problem is with the information you've given. But I personally think this is probably caused by your data. Did you initialize your Raindrop model properly? Please show me your code here so I can see if I can help further. You can also raise a discussion in our Slack community to chat instantly.

**Comment by WenjieDu** [comment] 2023-08-01 06:19
@max6457 Hi Max, I didn't receive further feedback from you in the past two weeks. Just want to check with you if you have solved the problem.

**Comment by max6457** [comment] 2023-08-04 18:51
Hello, thanks for your response and I wanted to apologize for my late reply. I am currently working on the data preprocessing, because this is the most important part for the project and here can be done a lot of mistakes. I will reach out with updates, I think I will be able to try to train the next model in a few days. Thanks a lot!

**Comment by WenjieDu** [comment] 2023-08-07 02:06
You can also take a look at the tutorials in https://github.com/WenjieDu/BrewPOTS to learn how to use PyPOTS.

**Comment by WenjieDu** [comment] 2023-08-08 16:47
I'm closing this issue. If you @max6457 have any follow-up, welcome to reopen it.

**Closed by WenjieDu** 2023-08-08 16:47 UTC
Labels: question
